name: Deploy

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Deploy to server
        uses: Techie-Pi/node-vps-deployment@main
        with:
          remote-path: "~/remote-path"
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          password: ${{ secrets.PASSWORD }}
          pm2-id: "PM2 ID"
